const topicsOfInterest = [
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Data Science",
    "Big Data",
    "Cybersecurity",
    "Blockchain",
    "Cryptocurrency",
    "Web Development",
    "Frontend Development",
    "Backend Development",
    "Fullstack Development",
    "Cloud Computing",
    "DevOps",
    "Mobile App Development",
    "iOS Development",
    "Android Development",
    "Game Development",
    "Virtual Reality",
    "Augmented Reality",
    "Mixed Reality",
    "Metaverse",
    "Quantum Computing",
    "Bioinformatics",
    "Genomics",
    "Neuroscience",
    "Psychology",
    "Philosophy",
    "Sociology",
    "Political Science",
    "Economics",
    "Finance",
    "Investing",
    "Stock Market",
    "Trading",
    "Entrepreneurship",
    "Startups",
    "Venture Capital",
    "Business Strategy",
    "Marketing",
    "Digital Marketing",
    "SEO",
    "Content Marketing",
    "Social Media",
    "E-commerce",
    "Product Management",
    "Project Management",
    "Leadership",
    "Productivity",
    "Self-Improvement",
    "Time Management",
    "Health",
    "Fitness",
    "Nutrition",
    "Mental Health",
    "Meditation",
    "Yoga",
    "Sports",
    "Football",
    "Basketball",
    "Cricket",
    "Tennis",
    "Music",
    "Film",
    "Television",
    "Photography",
    "Art",
    "Literature",
    "History",
    "Geography",
    "Travel",
    "Languages",
    "Culture",
    "Religion",
    "Islamic Studies",
    "Ethics",
    "Climate Change",
    "Sustainability",
    "Renewable Energy",
    "Astronomy",
    "Space Exploration",
    "Astrobiology",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Engineering",
    "Architecture",
    "Design",
    "Fashion",
    "Cooking",
    "Baking",
    "Gardening",
    "DIY",
    "Home Improvement",
    "Pets",
    "Technology News",
    "Gadgets",
    "Programming Languages",
    "JavaScript",
    "Python",
    "C++",
    "Java",
    "Rust",
    "Go",
    "Swift",
    "Kotlin",
];

const AppConstant = {
    topicsOfInterest,
};

export default AppConstant;
